### ISSUE TITLE
how to handle testing when auto accept is enabled in acapy?

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#129]
The issuer tests still contain a leftover todo related to auto accept being enabled in python. Is auto accept just enabled for development? In that case, maybe we should try to remove the unneeded auto accept configs in ACA-Py to be able to better test.

```
# TODO check for the correct response when state is credential_received
# We can't complete this with auto accept enabled
```

@morrieinmaas any thoughts on this?

## Task List

- [x] Connections (#165)
- [ ] Credentials
- [ ] Proofs -- should be done as part of present proof

**Comment by morrieinmaas** [comment]
@TimoGlastra There were discussions along those lines (no pun intended) already. IMHO this is a bit tricky because depending on whether or not auto-accept si enabled the flow changes. We left it as auot-accept for time being for simplicity reasons. I guess we could create unit tests to mock out either case. for e2e/integration tests we could set a flag and test which case applies, or provide another container with different setting, or restart the container. All of the latter ones don't sound appealing to me. 
I guess either way a step forward is to set auto_accept to false as I doubt True would be a likely setting in production. Then write tests around that.
