### ISSUE TITLE
Roles generalisation to tenants 

### ISSUE THREAD

**Issue by lohanspies** [didx-xyz/aries-cloudapi-python#217]
Hi @TimoGlastra @morrieinmaas @wip-abramson 

At the moment the stack has the concept of the following roles:

- Yoma
- Ecosystem
- Ecosystem-Admin
- Member
- Member-Admin

Should we not generalise the roles to only include:

- Governance
- Tenant
- Tenant-Admin

Let us know, unless we are missing something obvious.

**Comment by TimoGlastra** [comment]
Yes I 100% agree with this. We have kept it this way because the infrastructure was initially set up like this (see old architecture in wiki: https://github.com/didx-xyz/aries-cloudapi-python/wiki/Architecture), but it will make the infrastructure way less complex and also less yoma specific.

@morrieinmaas May be good to create an updated diagram of the stack and how components relate to each other once we have updates the roles

**Comment by TimoGlastra** [comment]
I'll address this once https://github.com/didx-xyz/aries-cloudapi-python/pull/219 has been merged

**Comment by morrieinmaas** [comment]
Also agree with this. @TimoGlastra I'll update the diagram

**Comment by morrieinmaas** [comment]
@lohanspies I'm fixing the broken things in the PR currently

**Comment by TimoGlastra** [comment]
> @wip-abramson is the reduction of roles something you are willing to take on? 

@wip-abramson are you already working on this? Don't want to do work that's already been worked on

**Comment by lohanspies** [comment]
@TimoGlastra @morrieinmaas we can close this issue as it is already completed.
