### ISSUE TITLE
Event Management

### ISSUE THREAD

**Issue by lohanspies** [didx-xyz/aries-cloudapi-python#248]
Hi, @morrieinmaas @TimoGlastra quick question.

How different is our implementation of webhooks vs the BVGov repo implementation https://github.com/bcgov/aries-acapy-plugin-redis-events?

Could we perhaps just use the BCGov implementation? Pros / Cons?

**Comment by morrieinmaas** [comment]
Hey @lohanspies. I'll have a closer lok at their implementation as I'm not 100% familiar with it and don't wan to bs you with half-knowledge from the top of my head.

Regarding out implementation though we do some processing of the webhooks to only keep/show the relevant information and the are ordered by topic and wallet

**Comment by lohanspies** [comment]
Great. Let me know when you get a chance.

**Comment by morrieinmaas** [comment]
Hey @lohanspies,

I've had a look at the BCGov implementation. Here's some thoughts on that:

PROs:
* more configuration options (standard, relay, mediator, relay[direct response])
* maintained by someone else (BCGov)
* Webhooks exactly like aca-py
* Uses redis pool (multiple instances)
* Only needs config to run

CONs:
* All of the PROs
* less control
* We loose customization of webhook data
* Filter mechanism is different/less customizable

In more detail:
Both implementations have their(dis-)advantages. In the end it boils down to what you want/think is best really. Also certain issues can be addressed. For instance, the fact that the BCGov implementation uses a redis pool instead of one instance (probably allowing for more throughput) we could also fairly easily set up for our implementation. I've also named all advantages as disadvantages because either way some work will go into it - switching to BCGov implementation or updating our implementation. Both are valid choices with slightly different outcomes. I would ask myself:

* Do I want to have the current implementation that offers more customization with respect to webhook content (filtered) and is integrated with the models in cloudapi
  * or do I want to switch to the BCGov implementation and
    * do the plumbing in cloudapi to not expect the "nicer" models and filtered output
    * have a pretty flexible webhook relay maintained by bcgov (less work for you/us) BUT
    * looses custom behaviour and processing (potentially we could recreate some of it on top of BCGov implementation - but extra work, unknown amount of effort) - which is better - medium/long term?
    * if we want custom behaviour within that BCGov relay we'd have to maintain a fork which voids the advantage of having it maintained by someone else - if so, do we want that?
    * implement certain advantages (using redis pool instead of single instance) into the our implementation - is that worth it?
    * using a redis pool/their implementation also adds quite a few more resource hungry containers (might be bad for development/might be good for production - can't really give too  qualified an answer to that) - is that ok?

In summary, either way is fine and comes with it's own advantages. In favour of the BCGov implementation, I'd say mainly it's maintained by them (the authors of aca-py) so one can assume it's quite decent. That said, using that would mean we'd have to make some changes to the current implementation (mainly because of custom models and subscribe mechanism) and we loose some of the granular control and niceties we created in our implementation. In the medium/long run it's questionable which one is better. "Better" here depends on a few things such as how many resources in terms of developers maintainers will be working on this. Do you rather want to not have to maintain (and further develop) the current custom implementation and live with the "what-you-get" (no custom models, and subscribe mechanism provided) from the BCGov implementation or do you want to have more granular control and niceties from the custom implementation. So, overall, I'd say either are options, either way is work.

Also, if anything is unclear or you want further feedback, just let me know.
