### ISSUE TITLE
Check and refactor endpoints 

### ISSUE THREAD

**Issue by morrieinmaas** [didx-xyz/aries-cloudapi-python#38]
The recent changes introduced in #11 need to be implemented for all endpoints and checked for breaking the work flow.

**Comment by morrieinmaas** [comment]
Needs team discussion. The current merge of #11  aka #9 has introduced some changes that at best will essentially halt refactoring the rest of the code following the introduced changes until general endpoint layout is more finite. 

Generally, outsourcing business logic away from the endpoint router definition itself is fine to some extend. However, having to pass all header args and/or params from the router endpoint definition into another function (basically 1:1) is tedious, (arguably) more confusing, and unnecessary repetition of code (utils and facade refactors imho make sense - core dowsn't so much). This either needs re-thinking in the sense that maybe we're doing something wrong by passing so many args in the first place and that should really be a JSON object as opposed to several args. Or  I'm not seeing the obvious, clever/elegant way the merge is suggesting. TB discussed.

**Comment by michaelwiles** [comment]
I prefer separating out the router in any case, even if it means things are a little as you say "tedious". The bottom line is having "core" which is framework agnostic is important enough in its own right in my opinion.

But having said that, if we move to using fast api dependencies then things are a lot simpler as a lot of the values passed are not longer necessary as what is passed in is what has been created based on those values. In other words, we will no longer have to pass in all the headers
.

**Comment by morrieinmaas** [comment]
Yeah, "tedious" shouldn't be an excuse. It's more about not ending up with things like this (example):

```python
@router.post(
    "/write-schema-and-credential-definition",
    tags=["credentials"],
    response_model=SchemaResponse,
)
async def write_credential_schema(
    schema_name: str,
    schema_version: str,
    schema_attrs: List[str] = Query(None),
    api_key: Optional[str] = Header(None),
    wallet_id: Optional[str] = Header(None),
    tenant_jwt: Optional[str] = Header(None),
):

try:
    result = await write_cred_schema_in_core(locals())  # or even passing them in explicitly
except:
...
```

and then having a a function in core eg:

```python
async def write_cred_schema_in_core(*args, **kwargs):  # or redefining the args here all over again
   result_1 = await having_fun_accessing_parent_args(abstruse_parent_args_that_arent_obvious_here)
   ....  
   result_n = having_fun_for_the_nth_time_accessing_parent_args(abstruse_parent_args_that_arent_obvious_here)
   return something_useful
```

So maybe I'm not seeing the good way to go here. Just want to avoid the above example.

**Comment by morrieinmaas** [comment]
Open for suggestions here really. If there is a good way to keep /core and not having to following something along the lines of the above example, please, provide another example.
 
After some time of trying to trying to mend what's there into this pattern I personaly would refrain from it alltogether. If there is a better way than factoring out the logic into utils and facades (this makes sense), please, do tell/propose. Just this refactoring into /core/{wallet.py, verifier.py, ...} to essentially do the same things in a different place under a different name and passing lots of params has more downsides to me than benefits. It adds complexity, makes following the code more confusing and as per example above introduces the necessity to obfuscate logic that was clear prior.

Any help and constructive feedback welcome.

**Comment by michaelwiles** [comment]
I've been building my api's this way for 20 years and what can I say, I like it.

It's something akin to the "[service layer pattern](https://martinfowler.com/eaaCatalog/serviceLayer.html)" - where the router is the "service layer" and the core is the business logic.

I feel is is a worthwhile a pattern or approach to use when building api's for the following reasons:

1. it separates concerns - the service layer (router in this case) is responsible for exposing the functionality to the outside world and that is where the fast api dependency. That is the focus of that context. When working there all you need to think about is how this method is exposed to the world - and other fast api mechanism, like for example, fast api dependencies. When working in "core" all you need to think about is meeting the business requirement of the call - no fastapi dependency to think about
2. It means you can test the "core" code without worrying about what web framework is being used
3. It means you can add for example, logging, and you only need to add it to the service layer.
4. It means if you want to add security you only add that in the service layer - core doesn't have to worry about (obviously won't work for all cases but will for cases where only a specific role is required for access to a method).
5. Means you can orchestrate fairly easily. In core you have all your transactions and if you need to call two "transactions" to achieve something you can. For example, the create wallet and assign public did - that can be 2 or 3 method calls into core and be exposed by one service layer method.
6. Means you can change your framework without affecting your core code.
7. Means you can expose your core logic by other means again without having to change your core code.
8. Means you can easily expose the same core method to a different end point - maybe with different security requirements
9. The data payload structure and or format can be changed without changing the core methods. Obviously adding a field would require core to be changed but we can remove a field and the core methods don't change - though this only really works when this pattern is extended such that there is a dto model (i.e. there is a model that the api uses to interact with the outside world and another model that is used internally by the api) - again separating concerns. The internal model focuses on the internal needs and the external model focuses on the external needs. Fastapi does a _very_ good job of this when you use it along with sql alchemy. It pretty much follows and enables this dto pattern very well. I'm not suggesting we adopt this approach as well.
10. Methods can be "stacked" i.e. one service call can call two methods and return results without changing the core methods.
11. Exception and error handling need not be done in core and can thus be done[ consistently in the router or service layer.](https://github.com/didx-xyz/aries-cloudapi-python/blob/da5bb37ffbb369cacad168e0059a6feed68c429b/app/routers/wallet.py#L56)

Yes there's a price to pay with because of the extra layer of abstraction that seems more trouble than its worth from some perspectives - if you don't see the above points as useful then yes, you might find it cumbersome.

There is some argument to be made that says we don't need this layer - at least now - yes, but saying we will add this layer when we need it doesn't really work as in my experience that never happens. It's too expensive to add this layer later but if we've already got it and we need it, we will have it.

Is my approach a relic of the other languages and frameworks I've worked on? No, I don't think so. I feel that building api's with this pattern is a good thing no matter the language or framework you're building on. 

And are we actually passing a lot of parameters? No - I've used this pattern when passing upwards of 5 - 10 parameters and have still felt it's worth it. Is a parameter object necessary? not really in python as python has keyword parameters and also has no method overloading so a wrapper object to contain the parameters is not worth it.

And apropos the example - using *args and **kwargs is defoes not an option. We _must_ include all the parameters the method in core takes quite clearly. The "core" context method must be _more_ clear than the service layer method. In the service layer this would be acceptable (*args and **kwargs) but certainly not in the core context.

Does it add complexity? I don't think so. What it does do is take 1 problem and make it two smaller problems. So it breaks one big problem into two smaller problems - thereby reducing complexity because I now have two separate smaller problems where I can focus on one to the exclusion of the other.

**Comment by morrieinmaas** [comment]
Cool, thanks for the elaborate answer (partially to questions I didn't ask). We can agree to disagree then. Again, I do see some of the benefits you mention - doing otherwise would be denying the obvious. However, I disagree with some, for instance the part about *args, **kwargs - it's never been meant as an argument against including all params. I just thinks it makes for ugly code. In the end I guess it's a matter of preference and style. Similarly we had parting views on using classes previously, where I just think making everything a class (eg ledger delegate or introducing [uplink](https://github.com/prkumar/uplink)) aka being very OOP for the sake of being OOP is not a pattern I want to follow. 

But it's ok for me to disagree. And please don't get me wrong, there's a lot of cool things you've introduced to the project and comments you gave for improving my code.

**Comment by michaelwiles** [comment]
So I'm happy to forgo this pattern - in the interests of moving forward and harmony. It's not something that I'm "go to the stake" for...

But if we don't use this pattern I would definitely not want to have a folder called "routers" and have the business logic in there.

Thought we'd take inspiration from our solidified api definition:

So a proposed folder structure:

admin
- governance
-   dids.py
-   schemas.py
-   wallets.py

I'd also be okay with this:

admin
- governance
- - dids
- -  router.py (or something else - not entirely happy with calling it router but at least the reader know where to start - and it seems to be somethign of a convention)
- - schemas
- -  router.py
- wallets
-  router.py

Be very readable for the dev coming in.

And both are similar to the way acapy is structured (second one more).

I'm not sure which one I prefer - both options have their strengths and weaknesses - probably the former is better since there's less folders. The latter would be better when more code is requried and we need more than one module to hold it. If you look at acapy code it follows this pattern (the second one). If a router.py is required then the second option as it has that.

**Comment by morrieinmaas** [comment]
Cool. Very much appreciate the flexibility! Thank you. Both suggestions look good at a first glimpse, but let me have a look tomorrow morning before so I can make a more educated comment😅
