### ISSUE TITLE
Build reference architecture for create_public_did call on wallet

### ISSUE THREAD

**Issue by michaelwiles** [didx-xyz/aries-cloudapi-python#9]
I'm going to take this call and flesh out a suggested reference architecture for us to shake a stick at (critique)

**Comment by morrieinmaas** [comment]
@michaelwiles @vineeth14 Not really sure what is left on this issue? Please clarify and I'll do the changes 🙏

**Comment by mrcbond88** [comment]
We think this might be done already. @michaelwiles please can you confirm for @morrieinmaas

**Comment by mrcbond88** [comment]
@michaelwiles We need to get this bad boy merged in please? Seems it's causing a bit of a roadblock. Once it's in we'll also need a fair amount of refactoring.

**Comment by morrieinmaas** [comment]
@michaelwiles I had to unmerge this, because the proposed changes break for instance the `/wallets/create-pub-did` endpoint, for a start. I haven't tried more endpoints but I suspect there will be other errors. 

Also, should've maybe commented on that earlier but overlooked that somehow. I don't think most people using this right now want daemon mode for the compose startup. Hence, I'd not make the changes to the start/up section in manage script. At least at this stage the terminal output comes in very handy. If you are unhappy with this spamming your terminal you could just open another shell or defer it to the background eg with `nohup ./manage.sh start &`.

**Comment by michaelwiles** [comment]
what is the issue with the /wallets/create-pup-did endpoint? are you talking about the change to the api key? I thought you asked that it is received from the client? 

I'm happy to put that back

**Comment by morrieinmaas** [comment]
Closed by #11
